# Excluded files
exclude:
- README.md
- LICENSE
- CNAME

# Included files
include:
- _redirects

# Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-seo-tag
- jemoji

# SCSS
sass:
  style: :compressed

# Permalinks
permalink: pretty

jekyll-mentions: https://twitter.com

# Site info
title: "John Lee"
name: "John Lee"
description: "Feel free to contact me if you find anything interesting!"
logo: "https://avatars.githubusercontent.com/u/88058124?s=300"

# SEO > twitter name meta
twitter:
  username: chunlee_john

# SEO > site alias meta
social:
  links:
    - https://twitter.com/chunlee_john
    - https://www.linkedin.com/in/chun-john-lee/
    - https://github.com/blackjlc

# SEO > author meta
author: chunlee_john